Implement reset method for ProfilerExtension
EmanueleMinotto/TwigCacheBundle pull request #21
Opened 2018-01-17 15:11 UTC by ahilles107

Fix Symfony 3.4 depreciation

2018-01-17 16:57 UTC, sweoggy commented
Related issue #20

2018-01-18 09:00 UTC, ahilles107 commented
@EmanueleMinotto - can you look at it?

2018-01-23 12:11 UTC, sweoggy requested changes

2018-01-23 12:11 UTC, sweoggy commented on Twig/ProfilerExtension.php
> +
Unnecessary white spaces

2018-01-23 12:11 UTC, sweoggy commented on Twig/ProfilerExtension.php
> +    public function reset()
Add PHPDoc

2018-01-29 15:30 UTC, ahilles107 commented
@sweoggy fixed.

2018-02-13 10:03 UTC, Gemineye commented
Any news?!

2018-03-03 22:58 UTC, mikemix commented
Any news? :(

2018-03-14 14:41 UTC, ahilles107 commented
Hey, 

we wan't to use this bundle in Symfony >=4. Please look at it and merge if possible.

2018-03-14 16:04 UTC, sweoggy commented
Might be worth creating an active fork, has been almost three months now.

2018-03-29 15:04 UTC, merged